name: "Compile Dotfiles"
on:
  push:
    branches:
    - main

jobs:
  compile_dotfiles:
    name: Compile Dotfles
    runs-on: macos-latest
    steps:
      - name: Checkout Output Branch
        uses: actions/checkout@v3
        with:
          ref: compiled
      
      - name: Cleanup Working Directory
        run: | 
          cp README.md ~/README.md
          git rm -rf .
          cp ~/README.md README.md

      - name: Install Chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Initialise Dotfiles
        run: ./bin/chezmoi init harryob

      - name: Output Dotfiles
        run: mkdir output && ./bin/chezmoi apply --destination .

      - name: Move Output and Commit
        run: |
          rm -rf bin
          git config user.name Compiler
          git config user.email actions@github.com
          git add .
          git commit -m "compiled dotfiles"
          git push
